
name: Execute UI Tests

on:
  workflow_call:
   inputs:
    browser:
      required: true
      type: string
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run ${{ inputs.browser }} tests
      run: mvn clean test -Dbrowser=${{ inputs.browser }} -DheadlessMode=true --file pom.xml
    
    # Display Junit test results in dashboard
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "target/surefire-reports/TEST-*.xml"
      if: always()

    # The next steps will deploy the generated allure report to github pages
    
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
        
    # Show the report link   
    - name : Report URL
      run: echo "https://alapisco.github.io/Saucedemo-UI-testing-framework/${{ github.run_number }}"      
